#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cardapio.Resource", IsApplication=true)]

namespace Cardapio
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appComida = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Bahia = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Palmeiras = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int santos = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Saopaulo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int timeflamengo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int vitoriaba = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060021
			public const int IdGridFotos = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int IdGridSimples = 2131099682;
			
			// aapt resource value: 0x7f060018
			public const int ImgGridImagem = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int TxtNomeGridImage = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int autoCompleteTextView = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int btnAviso = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int btnEnviar = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int btnExGridImage = 2131099671;
			
			// aapt resource value: 0x7f060006
			public const int btnExemplo3 = 2131099654;
			
			// aapt resource value: 0x7f060016
			public const int btnExemploUm = 2131099670;
			
			// aapt resource value: 0x7f060007
			public const int btnFone = 2131099655;
			
			// aapt resource value: 0x7f060020
			public const int btnGridSimples = 2131099680;
			
			// aapt resource value: 0x7f060009
			public const int btnLogin = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int btnLoginComBD = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int btnRegistrar2 = 2131099653;
			
			// aapt resource value: 0x7f06001f
			public const int btnRegistrarReg = 2131099679;
			
			// aapt resource value: 0x7f06000f
			public const int btnVoltar = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int btnWeb = 2131099656;
			
			// aapt resource value: 0x7f06000e
			public const int btnsLoguin = 2131099662;
			
			// aapt resource value: 0x7f060004
			public const int btnsLoguin2 = 2131099652;
			
			// aapt resource value: 0x7f060012
			public const int butComTres = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int lblEstado = 2131099667;
			
			// aapt resource value: 0x7f06000a
			public const int lblNome = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int lblPosLogin = 2131099674;
			
			// aapt resource value: 0x7f06000c
			public const int lblSenha = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int lblSenha2 = 2131099650;
			
			// aapt resource value: 0x7f06001d
			public const int lblSenhaReg = 2131099677;
			
			// aapt resource value: 0x7f060000
			public const int lblUser = 2131099648;
			
			// aapt resource value: 0x7f06001b
			public const int lblUserReg = 2131099675;
			
			// aapt resource value: 0x7f06000b
			public const int txtNome = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int txtSenha = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int txtSenha2 = 2131099651;
			
			// aapt resource value: 0x7f06001e
			public const int txtSenhaReg = 2131099678;
			
			// aapt resource value: 0x7f060001
			public const int txtUsuario2 = 2131099649;
			
			// aapt resource value: 0x7f06001c
			public const int txtUsuarioReg = 2131099676;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ExemploDois = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ExemploUm = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListViewComGoogle = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int modeloGrid = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PosLogin = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Registrar = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int UiGridComFoto = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int UiGridSimples = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int aviso = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int avisobtn = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int manolo_Theme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
